# Generated by Django 6.0.3 on 2026-03-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0002_paciente_cpf_paciente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='dentista',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentista',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
