# Generated by Django 6.0.3 on 2026-03-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0003_dentista_cpf_dentista_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Gerente'), ('2', 'Dentista'), ('3', 'Paciente')], default='1', max_length=1),
        ),
    ]
