# Generated by Django 6.0.3 on 2026-03-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0006_alter_customuser_user_type_recepcionista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcionista',
            name='created_at',
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
