# Generated by Codex on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica_app", "0008_alter_dentista_address_alter_dentista_cro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Nome completo"),
        ),
    ]

